apiVersion: apps/v1
kind: Deployment
metadata:
  name: csk
  labels:
    app: csk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csk
  template:
    metadata:
      labels:
        app: csk
    spec:
      containers:
      - name: microservice-container
        image: docker.io/mfk267/gsd:csk2024
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: csk
spec:
  type: ClusterIP
  selector:
    app: csk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080