apiVersion: apps/v1
kind: Deployment
metadata:
  name: srh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srh
  template:
    metadata:
      labels:
        app: srh
    spec:
      containers:
      - name: srh
        image: docker.io/mfk267/gsd:srh2024
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: srh
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: srh